### ISSUE TITLE
Linux aarch64 support

### ISSUE THREAD

**Issue by Martin-Schlodinski** [moia-oss/aws-cfg-generator#51]
Hi!
I'd appreciate if the releases of the aws-cfg-generator tool would also contain a linux version for aarch64 architecture. This would allow me to use it in a VM on my Mac M1. After looking at the release.yaml and the Makefile sadly I have no idea where to add this option (otherwise I'd have opened a PR myself).
Thanks in advance!
Martin

**Comment by cbrgm** [comment]
Hey Martin, thanks for reaching out and sorry that it took some time! We can provide an aarch64 release for sure!

**Comment by johannes-gehrs** [comment]
Should be done with the latest release.

**Comment by Martin-Schlodinski** [comment]
wow thanks so much @cbrgm @johannes-gehrs !!! :) and no worries, I was able to compile it on my own ... but others ran into the same issue. We'll all appreciate the new version support! Thanks once again!
