### ISSUE TITLE
Configuration file to make the initial IAM user/role optional

### ISSUE THREAD

**Issue by nitrocode** [moia-oss/aws-cfg-generator#66]
It would be nice to make the IAM user/role optional with some sort of configuration file.

From the README, it seems like the IAM user/role is only required to get the account IDs.

> In order to name profiles correctly, aws-cfg-generator will attempt to call organizations.ListAccounts and match that with account IDs in the roles the user has access to.

If there is a configuration file that contains structured data with all the account IDs (and perhaps additional information), then the IAM user/role could be omitted.

**Comment by bemica** [comment]
I'm not sure I understand entirely. An IAM user's credentials are also needed to discover what IAM roles the user has access to. The intent is to generate one profile per role that the user has permission to call `iam:AssumeRole` on.

We could get around calling `ListAccounts` with such a configuration file, and this might be useful especially if a user has permissions to assume a role in a different organization than the one they belong to, but this wouldn't get rid of the need to have an IAM user's credentials from the beginning.

Does this resolve the confusion and if not could you clarify your intent further?

**Comment by bemica** [comment]
Hey @nitrocode I'll close this issue for now but if the problem can be clarified later we can revisit it

**Comment by nitrocode** [comment]
Hmm. I see what you mean.

I was hoping that there could be two ways to use the tool.

- Current method to hit the APIs with a user to autodiscover roles to generate profiles in the configuration file
- Supply the roles without autodiscovery, basically autodiscovery in a separate tool, and then generate profiles in the configuration file
